sudo: required
dist: trusty
language: node_js

node_js:
  - "5"

env:
  global:
    - "DBUS_SESSION_BUS_ADDRESS=/dev/null"
    - "DISPLAY=:99.0"
    - "CHROME_BIN=chromium-browser"

before_script:
  - "sh -e /etc/init.d/xvfb start"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g karma

script: karma start karma.conf.js --single-run
