language: node_js

node_js:
  - 5
  - 6
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3

cache:
  directories:
    - node_modules

before_script:
  - npm install -g angular-cli
  - npm install -g karma
  - npm install

script: ng test 
