sudo: required
dist: trusty
language: node_js

node_js:
  - "4"

os:
  linux

env:
  global:
    - "DBUS_SESSION_BUS_ADDRESS=/dev/null"
    - "DISPLAY=:99.0"
    - "CHROME_BIN=chromium-browser"

before_script:
  - "sh -e /etc/init.d/xvfb start"

cache:
  directories:
    - node_modules

before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "--no-sandbox" > ~/.config/chromium-flags.conf; fi'
  - npm install -g npm
  - npm config set spin false
  - npm config set progress false

install: npm install --no-optional

before_script: npm install -g karma

script: karma start karma.conf.js --single-run